#!/bin/sh

find_key() {
prefix=${PASSWORD_STORE_DIR}
pass_path=$(find "$prefix"/"$1"/ -type f -name "$2*")
[ -z "$pass_path" ] && echo "No password found"
pass_path=$(realpath --relative-base="$prefix" "$pass_path")
pass_path=$(echo "$pass_path" | rev | cut -f 2- -d '.' | rev)
pass "$pass_path"
}

open_error() {
  echo "Can't open tomb, try to run pass open -d"
  sudo swapon -a
  exit 1
}


tomb list >/dev/null 2>&1 || sesame
find_key "$@"
