#!/usr/bin/env bash


extract_key() {
shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/*/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | sed 's/\//: /g' | dmenu "$@"| sed 's/: /\//g')
password=$(find "${PASSWORD_STORE_DIR}" -path '/*'"$password"'*' -printf %P | rev | cut -f 1 --complement -d '.' | rev)

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
fi
}

open_error() {
  echo "Can't open tomb, try to run pass open -d"
  sudo swapon -a
  exit 1
}
sudo swapoff -a
pass open 2>/dev/null || open_error
extract_key "$@"
pass close 2>/dev/null || echo "Tomb hasn't been closed properly"
sudo swapon -a
