#!/bin/sh

# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="${XDG_CONFIG_HOME}/shortcutrc"
b_shortcuts="${XDG_CONFIG_HOME}/lynx/shortcuts.conf"
gb_shortcuts="${XDG_CONFIG_HOME}/vimb/shortcuts.conf"

# Remove, prepare files
rm -f "$shell_shortcuts" "$b_shortcuts" "$gb_shortcuts" 2>/dev/null
# printf "# vim: filetype=sh\\n" > "$fish_shortcuts"
# printf "# vim: filetype=sh\\nalias " > "$shell_shortcuts"
# printf "\" vim: filetype=vim\\n" > "$vifm_shortcuts"

# Format the `directories` file in the correct syntax and sent it to all configs.
eval "echo \"$(cat "${XDG_CONFIG_HOME}/directories")\"" | \
awk "!/^\s*#/ && !/^\s*\$/ {
  printf(\"%s() { cd %s && ls -a; }\n\",\$1,\$2)   >> \"$shell_shortcuts\" ;
  printf(\"config.bind(';%s', \42set downloads.location.directory %s ;; hint links download\42) \n\",\$1,\$2) >> \"$b_shortcuts\" }"

# Format the `files` file in the correct syntax and sent it to configs.
eval "echo \"$(cat "${XDG_CONFIG_HOME}/cfiles")\"" | \
awk "!/^\s*#/ && !/^\s*\$/ {
  printf(\"%s() { \$EDITOR %s; }\n\",\$1,\$2)  >> \"$shell_shortcuts\" ;
  printf(\"map %s shell \$EDITOR %s \n\",\$1,\$2)  >> \"$b_shortcuts\" ;
  printf(\"map %s shell \$EDITOR %s \n\",\$1,\$2)  >> \"$gb_shortcuts\" }"
